### ISSUE TITLE
Mu-Th-Ur speaks as "Maman:" in non-french localizations

### ISSUE THREAD

**Issue by TimoLemburg** [ShazProd/alien-mu-th-ur#1]
Great project, I love it.

Since I am using Mu-Th-Ur in another language then french I would like to see that messages from Mu-Th-Ur don't have "Maman:" as fixed text in fron of the message, hard coded in the main.js.

Could this be localized or changed to "Mu/Th/Ur" in the en and de languages? Or maybe this could be a configurable field in the settings?

**Comment by ShazProd** [comment]
Hello thank you for your feedback, the corrections have been made you can update it, 

everything is internationalized

Enjoy the module

**Comment by ShazProd** [comment]
Hello thank you for your feedback, the corrections have been made you can update it,

everything is internationalized

Enjoy the module
